package com.nsdl.beckn.common.enums;

public enum AuditType {

	REQUEST_BY_GATEWAY,
	REQUEST_TO_GATEWAY,
	RESPONSE_BY_GATEWAY,
	RESPONSE_TO_GATEWAY,
	ACK_BY_GATEWAY,
	NACK_BY_GATEWAY,
	INVALID_RESPONSE_BY_GATEWAY,
	ERROR_CALLING_GATEWAY,
	ACK_TO_GATEWAY,
	NACK_TO_GATEWAY,

	REQUEST_TO_SELLER,
	RESPONSE_BY_SELLER,
	ACK_BY_SELLER,
	NACK_BY_SELLER,
	INVALID_RESPONSE_BY_SELLER,
	ERROR_CALLING_SELLER,
	BLOCKED_SELLER,
	ACK_TO_SELLER,
	NACK_TO_SELLER,

	REQUEST_BY_BUYER,
	RESPONSE_TO_BUYER,
	ACK_BY_BUYER,
	NACK_BY_BUYER,
	INVALID_RESPONSE_BY_BUYER,
	ERROR_CALLING_BUYER,
	BLOCKED_BUYER,
	ACK_TO_BUYER,
	NACK_TO_BUYER,
	;

	String type;
	AuditType() {
	}

	public String type() {
		return this.type;
	}

}
